# Site settings
title: Portfolio
email: brett.feeley217@gmail.com
url: https://github.com/brf217/brf217.github.io
description: "Brett's data science portfolio page"
keywords: "SQL, Python, R, Database, ETL, Web Scraping, Webscraping, AWS, Contracting, Data Science, Data Engineering, Business Intelligence, Snowflake, Denver"
skills: "Data Science | Data Engineering | BI Development"
meta_author: Feeley Brett

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d7d8d7
  primary-rgb: "24,288,156"
  secondary: 2c2d2c
  secondary-dark: 282928

# Footer settings
footer:
  copyright: 
  location: Location
  social: Contact #Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://www.linkedin.com/in/brettfeeley/
  - title: github
    url: https://github.com/brf217/samples/tree/main

# Postal address (add as many lines as necessary)
address:
  - line: Denver, CO

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
future: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
